up:
  - python: 3.6.4
  - pipfile

commands:
  test:
    run: example/manage.py test
  lint:
    run: flake8
  upload-release:
    run: rm -rf dist && python setup.py sdist bdist_wheel && twine upload dist/*
